name: Haskell CI

on:
  push:
    branches: [ 'main', 'ci', 'ci-uc', '*' ]
  pull_request:
    branches: [ 'main' ]
  release:
    types:
      - created
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:  [ 'ubuntu-latest', 'macOS-latest' ]
        ghc: [ '9.2', '9.4', '9.6', '9.8', '9.10', '9.12' ]

    env:
      cache-name: cabal-ghc
      target-config: --test-show-details=streaming --enable-tests --disable-benchmarks

    steps:
    - run: git config --global core.autocrlf false

    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: latest

    - name: Hackage index, Cache Key
      id: params
      shell: bash
      run: |
        ghc_version=$(ghc --numeric-version)
        cabal update
        echo "cache=${{ runner.os }}-build-${{ env.cache-name }}-${ghc_version}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}" > "$GITHUB_OUTPUT"
        echo "ghc_version=$ghc_version" >> "$GITHUB_OUTPUT"

    - name: Restore Cache
      uses: actions/cache/restore@v4
      if: ${{ github.ref_name != 'ci-uc' }}
      with:
        path: ~/.cabal
        key: ${{ steps.params.outputs.cache }}

    - name: Install doctest
      id: doctest-dep
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        if cabal install --offline --overwrite-policy=always doctest
        then
          echo "installed=false" >> "$GITHUB_OUTPUT"
        else
          cabal install doctest --overwrite-policy=always
          echo "installed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Install dependencies
      id: inst-dep
      shell: bash
      run: |
        if cabal build --offline --only-dependencies ${{ env.target-config }} all
        then
          echo "installed=false" >> "$GITHUB_OUTPUT"
        else
          cabal build --only-dependencies ${{ env.target-config }} all
          echo "installed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Save Cache
      uses: actions/cache/save@v4
      if: ${{ steps.inst-dep.outputs.installed == 'true' || steps.doctest-dep.outputs.installed == 'true' }}
      with:
        path: ~/.cabal
        key: ${{ steps.params.outputs.cache }}

    - name: Build
      run: cabal build ${{ env.target-config }} all

    - name: Run tests
      run: env DISABLE_V6_NS=1 cabal test ${{ env.target-config }} all

    - name: Run doctest
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        for package in $(cat cabal.project | sed 's/packages://g' | sed 's/dnsext-bowline//g')
        do
          env DISABLE_V6_NS=1 cabal repl --with-ghc=doctest ${{ env.target-config }} $package
        done
        env   DISABLE_V6_NS=1 cabal repl --with-ghc=doctest ${{ env.target-config }} dnsext-bowline:bowline

    - name: Install
      run: |
        cabal install dnsext-bowline
        mkdir dist
        if [ ${{ matrix.os }} == "macOS-latest" ] ; then
          cp -L ~/.cabal/bin/bowline  dist/bowline-mac-arm64
          cp -L ~/.cabal/bin/dug  dist/dug-mac-arm64
        elif [ ${{ matrix.os }} == "ubuntu-latest" ] ; then
          cp -L ~/.cabal/bin/bowline  dist/bowline-linux-amd64
          cp -L ~/.cabal/bin/dug  dist/dug-linux-amd64
        fi
    - name: Upload artifact
      if: ${{ matrix.ghc == '9.6' }}
      uses: actions/upload-artifact@v4
      with:
        path: |
          dist/*
        name: dnsext-bowline-${{ runner.os }}-${{ runner.arch }}
    - name: Github Releases
      if: gitHub.event_name == 'release' && matrix.ghc == '9.6'
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          dist/*
    - name: Homebrew-checksum
      id: checksum
      if: gitHub.event_name == 'release' && matrix.ghc == '9.6'
      run: |
        echo "::set-output name=sha256::$(sha256sum dist/dug-mac-arm64 | awk '{print $1}')"
    - name: Homebrew-version
      id: version
      if: gitHub.event_name == 'release' && matrix.ghc == '9.6'
      run: |
        echo ::set-output name=version::${{ github.ref_name }}
    - name: trigger Homebrew formulae update
      uses: peter-evans/repository-dispatch@v1
      if: gitHub.event_name == 'release' && matrix.ghc == '9.6' && runner.os == 'macOS'
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: thehajime/homebrew-tap
        event-type: update-brew
        client-payload: '{ "url": "${{ github.server_url }}/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/dug-mac-arm64", "sha256": "${{ steps.checksum.outputs.sha256 }}", "version": "${{ steps.version.outputs.version }}" }'
